package com.qxms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public void setDid(java.lang.Integer did) {
		set("did", did);
	}

	public java.lang.Integer getDid() {
		return get("did");
	}

	public void setParentDid(java.lang.Integer parentDid) {
		set("parent_did", parentDid);
	}

	public java.lang.Integer getParentDid() {
		return get("parent_did");
	}

	public void setParentDids(java.lang.String parentDids) {
		set("parent_dids", parentDids);
	}

	public java.lang.String getParentDids() {
		return get("parent_dids");
	}

	public void setDname(java.lang.String dname) {
		set("dname", dname);
	}

	public java.lang.String getDname() {
		return get("dname");
	}

	public void setManager(java.lang.String manager) {
		set("manager", manager);
	}

	public java.lang.String getManager() {
		return get("manager");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}

	public java.lang.Integer getCreateBy() {
		return get("create_by");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

	public java.lang.Integer getDelFlag() {
		return get("del_flag");
	}

}
