package com.qxms.model;

import com.qxms.model.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu();

	@Override
	public String toString() {
		return "PID:"+getParentId().toString()+"    ID:"+getMenuid().toString();
	}
	
	
}
