package com.qxms.model;

import com.qxms.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	private String[] role;

	public Department getDepartment() {
		String sql = "SELECT * FROM `qx_department` WHERE did = ?";
		
		return Department.dao.findFirst(sql,getDid());
	}

	public void setDepartment(Department department) {
		//this.department = department;		
	}

	public String[] getRole() {
		return role;
	}

	public void setRole(String[] role) {
		this.role = role;
	}
	
	
}
