package com.qxms.model;

import java.util.List;

import com.qxms.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	private String[] role;

	public Department getDepartment() {
		String sql = "SELECT * FROM `qx_department` WHERE did = ?";
		
		return Department.dao.findFirst(sql,getDid());
	}

	public void setDepartment(Department department) {
		//this.department = department;		
	}

	public String[] getRole() {
		return role;
	}

	public void setRole(String[] role) {
		this.role = role;
	}
	
	public List<Role> getRolelist(){
		String sql = "SELECT `a`.* FROM `qx_role` `a` "
				+ "LEFT JOIN `qx_user_role` `b` ON `a`.`roleid`=`b`.`role_id` "
				+ "LEFT JOIN `qx_user` `c` ON `c`.`uid`=`b`.`user_id` "
				+ "WHERE `c`.`uid`=?";		
		return Role.dao.find(sql, getUid());
	}
}
